export const CODING_QUESTION_REQUEST="CODING_QUESTION_REQUEST";
export const CODING_QUESTION_SUCCESS="CODING_QUESTION_SUCCESS";
export const CODING_QUESTION_FAIL="CODING_QUESTION_FAIL";


export const MULTIPLE_QUESTION_REQUEST="MULTIPLE_QUESTION_REQUEST";
export const MULTIPLE_QUESTION_SUCCESS="MULTIPLE_QUESTION_SUCCESS";
export const MULTIPLE_QUESTION_FAIL="MULTIPLE_QUESTION_FAIL";

export const CLEAR_ERRORS="CLEAR_ERRORS";