export const LOGIN_STUDENT_REQUEST="LOGIN_REQUEST";
export const LOGIN_STUDENT_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_STUDENT_FAIL="LOGIN_FAIL";

export const REGISTER_STUDENT_REQUEST="REGISTER_REQUEST";
export const REGISTER_STUDENT_SUCCESS="REGISTER_SUCCESS";
export const REGISTER_STUDENT_FAIL="REGISTER_FAIL";

export const LOAD_STUDENT_REQUEST="LOAD_STUDENT_REQUEST";
export const LOAD_STUDENT_SUCCESS="LOAD_STUDENT_SUCCESS";
export const LOAD_STUDENT_FAIL="LOAD_STUDENT_FAIL";

export const LOGOUT_STUDENT_SUCCESS="LOGOUT_SUCCESS";
export const LOGOUT_STUDENT_FAIL="LOGOUT_FAIL";

export const CLEAR_STUDENT_ERRORS="CLEAR_ERRORS";